# תרגול אמצע

In [2]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np

In [19]:
random_arr = np.random.randint(1, 50, size=(10))
random_arr

array([38, 40, 27, 25, 40, 20, 33, 20, 10,  8], dtype=int32)

In [6]:
random_arr.size

10

In [7]:
np.ndim(random_arr)

1

In [8]:
random_arr.dtype

dtype('int32')

In [21]:
random_arr = np.random.randint(10, 100, size=(2,5))
random_arr

array([[81, 11, 37, 51, 86],
       [62, 38, 29, 25, 80]], dtype=int32)

# שיעורי בית  

In [11]:
random_arr = np.random.randint(1, 50, size=(10))
np.mean(random_arr)

np.float64(16.9)

In [12]:
arr1 = np.array([[1,2],[3,4],[5,6]])
arr2 = np.array([[1,2],[3,4],[5,6]])
arr3 = np.add(arr1, arr2)
np.mean(arr3)

np.float64(7.0)

In [14]:
arr = np.random.randint(1, 100, size=(20))
condition = arr > 50
filtered_arr = arr[condition]
filtered_arr

array([76, 79, 93, 89, 66, 98, 92], dtype=int32)

In [17]:
arr = np.arange(1, 11)
np.random.shuffle(arr)
np.random.choice(arr, size=3, replace=False)

array([2, 4, 3])